/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.BankStatement;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankStatementRecord extends UpdatableRecordImpl<BankStatementRecord> implements Record3<Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.BANK_STATEMENT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.BANK_STATEMENT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>VBKA.BANK_STATEMENT.FILE_NAME</code>.
     */
    public void setFileName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VBKA.BANK_STATEMENT.FILE_NAME</code>.
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VBKA.BANK_STATEMENT.DATE_OF_UPLOAD</code>.
     */
    public void setDateOfUpload(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>VBKA.BANK_STATEMENT.DATE_OF_UPLOAD</code>.
     */
    public LocalDateTime getDateOfUpload() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BankStatement.BANK_STATEMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return BankStatement.BANK_STATEMENT.FILE_NAME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return BankStatement.BANK_STATEMENT.DATE_OF_UPLOAD;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFileName();
    }

    @Override
    public LocalDateTime component3() {
        return getDateOfUpload();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFileName();
    }

    @Override
    public LocalDateTime value3() {
        return getDateOfUpload();
    }

    @Override
    public BankStatementRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BankStatementRecord value2(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public BankStatementRecord value3(LocalDateTime value) {
        setDateOfUpload(value);
        return this;
    }

    @Override
    public BankStatementRecord values(Long value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankStatementRecord
     */
    public BankStatementRecord() {
        super(BankStatement.BANK_STATEMENT);
    }

    /**
     * Create a detached, initialised BankStatementRecord
     */
    public BankStatementRecord(Long id, String fileName, LocalDateTime dateOfUpload) {
        super(BankStatement.BANK_STATEMENT);

        setId(id);
        setFileName(fileName);
        setDateOfUpload(dateOfUpload);
    }
}
