/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.Booking;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookingRecord extends UpdatableRecordImpl<BookingRecord> implements Record6<Integer, String, Integer, LocalDate, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.BOOKING.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VBKA.BOOKING.FK_ACCOUNT</code>.
     */
    public void setFkAccount(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.FK_ACCOUNT</code>.
     */
    public String getFkAccount() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VBKA.BOOKING.FK_BANK_STATEMENT</code>.
     */
    public void setFkBankStatement(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.FK_BANK_STATEMENT</code>.
     */
    public Integer getFkBankStatement() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VBKA.BOOKING.BOOKING_DATE</code>.
     */
    public void setBookingDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.BOOKING_DATE</code>.
     */
    public LocalDate getBookingDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>VBKA.BOOKING.AMOUNT_IN_CENT</code>.
     */
    public void setAmountInCent(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.AMOUNT_IN_CENT</code>.
     */
    public Integer getAmountInCent() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>VBKA.BOOKING.BOOKING_AS_STRING</code>.
     */
    public void setBookingAsString(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING.BOOKING_AS_STRING</code>.
     */
    public String getBookingAsString() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Integer, LocalDate, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, Integer, LocalDate, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Booking.BOOKING.ID;
    }

    @Override
    public Field<String> field2() {
        return Booking.BOOKING.FK_ACCOUNT;
    }

    @Override
    public Field<Integer> field3() {
        return Booking.BOOKING.FK_BANK_STATEMENT;
    }

    @Override
    public Field<LocalDate> field4() {
        return Booking.BOOKING.BOOKING_DATE;
    }

    @Override
    public Field<Integer> field5() {
        return Booking.BOOKING.AMOUNT_IN_CENT;
    }

    @Override
    public Field<String> field6() {
        return Booking.BOOKING.BOOKING_AS_STRING;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFkAccount();
    }

    @Override
    public Integer component3() {
        return getFkBankStatement();
    }

    @Override
    public LocalDate component4() {
        return getBookingDate();
    }

    @Override
    public Integer component5() {
        return getAmountInCent();
    }

    @Override
    public String component6() {
        return getBookingAsString();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFkAccount();
    }

    @Override
    public Integer value3() {
        return getFkBankStatement();
    }

    @Override
    public LocalDate value4() {
        return getBookingDate();
    }

    @Override
    public Integer value5() {
        return getAmountInCent();
    }

    @Override
    public String value6() {
        return getBookingAsString();
    }

    @Override
    public BookingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BookingRecord value2(String value) {
        setFkAccount(value);
        return this;
    }

    @Override
    public BookingRecord value3(Integer value) {
        setFkBankStatement(value);
        return this;
    }

    @Override
    public BookingRecord value4(LocalDate value) {
        setBookingDate(value);
        return this;
    }

    @Override
    public BookingRecord value5(Integer value) {
        setAmountInCent(value);
        return this;
    }

    @Override
    public BookingRecord value6(String value) {
        setBookingAsString(value);
        return this;
    }

    @Override
    public BookingRecord values(Integer value1, String value2, Integer value3, LocalDate value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRecord
     */
    public BookingRecord() {
        super(Booking.BOOKING);
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(Integer id, String fkAccount, Integer fkBankStatement, LocalDate bookingDate, Integer amountInCent, String bookingAsString) {
        super(Booking.BOOKING);

        setId(id);
        setFkAccount(fkAccount);
        setFkBankStatement(fkBankStatement);
        setBookingDate(bookingDate);
        setAmountInCent(amountInCent);
        setBookingAsString(bookingAsString);
    }
}
