/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.CategoryMatcherRCategory;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryMatcherRCategoryRecord extends UpdatableRecordImpl<CategoryMatcherRCategoryRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY</code>.
     */
    public void setFkCategory(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY</code>.
     */
    public Integer getFkCategory() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER</code>.
     */
    public void setFkCategoryMatcher(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER</code>.
     */
    public String getFkCategoryMatcher() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY;
    }

    @Override
    public Field<String> field2() {
        return CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER;
    }

    @Override
    public Integer component1() {
        return getFkCategory();
    }

    @Override
    public String component2() {
        return getFkCategoryMatcher();
    }

    @Override
    public Integer value1() {
        return getFkCategory();
    }

    @Override
    public String value2() {
        return getFkCategoryMatcher();
    }

    @Override
    public CategoryMatcherRCategoryRecord value1(Integer value) {
        setFkCategory(value);
        return this;
    }

    @Override
    public CategoryMatcherRCategoryRecord value2(String value) {
        setFkCategoryMatcher(value);
        return this;
    }

    @Override
    public CategoryMatcherRCategoryRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryMatcherRCategoryRecord
     */
    public CategoryMatcherRCategoryRecord() {
        super(CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryMatcherRCategoryRecord
     */
    public CategoryMatcherRCategoryRecord(Integer fkCategory, String fkCategoryMatcher) {
        super(CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY);

        setFkCategory(fkCategory);
        setFkCategoryMatcher(fkCategoryMatcher);
    }
}
