/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.CategoryMatcherRCategory;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryMatcherRCategoryRecord extends UpdatableRecordImpl<CategoryMatcherRCategoryRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY</code>.
     */
    public void setFkCategory(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY</code>.
     */
    public Long getFkCategory() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER</code>.
     */
    public void setFkCategoryMatcher(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>VBKA.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER</code>.
     */
    public Long getFkCategoryMatcher() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY;
    }

    @Override
    public Field<Long> field2() {
        return CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY.FK_CATEGORY_MATCHER;
    }

    @Override
    public Long component1() {
        return getFkCategory();
    }

    @Override
    public Long component2() {
        return getFkCategoryMatcher();
    }

    @Override
    public Long value1() {
        return getFkCategory();
    }

    @Override
    public Long value2() {
        return getFkCategoryMatcher();
    }

    @Override
    public CategoryMatcherRCategoryRecord value1(Long value) {
        setFkCategory(value);
        return this;
    }

    @Override
    public CategoryMatcherRCategoryRecord value2(Long value) {
        setFkCategoryMatcher(value);
        return this;
    }

    @Override
    public CategoryMatcherRCategoryRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryMatcherRCategoryRecord
     */
    public CategoryMatcherRCategoryRecord() {
        super(CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY);
    }

    /**
     * Create a detached, initialised CategoryMatcherRCategoryRecord
     */
    public CategoryMatcherRCategoryRecord(Long fkCategory, Long fkCategoryMatcher) {
        super(CategoryMatcherRCategory.CATEGORY_MATCHER_R_CATEGORY);

        setFkCategory(fkCategory);
        setFkCategoryMatcher(fkCategoryMatcher);
    }
}
