/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.CategoryMatcher;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryMatcherRecord extends UpdatableRecordImpl<CategoryMatcherRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.CATEGORY_MATCHER.MATCHING_WORD</code>.
     */
    public void setMatchingWord(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.CATEGORY_MATCHER.MATCHING_WORD</code>.
     */
    public String getMatchingWord() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CategoryMatcher.CATEGORY_MATCHER.MATCHING_WORD;
    }

    @Override
    public String component1() {
        return getMatchingWord();
    }

    @Override
    public String value1() {
        return getMatchingWord();
    }

    @Override
    public CategoryMatcherRecord value1(String value) {
        setMatchingWord(value);
        return this;
    }

    @Override
    public CategoryMatcherRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryMatcherRecord
     */
    public CategoryMatcherRecord() {
        super(CategoryMatcher.CATEGORY_MATCHER);
    }

    /**
     * Create a detached, initialised CategoryMatcherRecord
     */
    public CategoryMatcherRecord(String matchingWord) {
        super(CategoryMatcher.CATEGORY_MATCHER);

        setMatchingWord(matchingWord);
    }
}
