/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.jooq.tables.records;


import de.VBKA.database.jooq.tables.UserTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTableRecord extends UpdatableRecordImpl<UserTableRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.USER_TABLE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.USER_TABLE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserTable.USER_TABLE.ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public UserTableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserTableRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTableRecord
     */
    public UserTableRecord() {
        super(UserTable.USER_TABLE);
    }

    /**
     * Create a detached, initialised UserTableRecord
     */
    public UserTableRecord(Integer id) {
        super(UserTable.USER_TABLE);

        setId(id);
    }
}
