/*
 * This file is generated by jOOQ.
 */
package de_2fVBKA_2fdatabase.tables.records;


import de_2fVBKA_2fdatabase.tables.BookingRCategory;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookingRCategoryRecord extends UpdatableRecordImpl<BookingRCategoryRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>VBKA.BOOKING_R_CATEGORY.FK_BOOKING</code>.
     */
    public void setFkBooking(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING_R_CATEGORY.FK_BOOKING</code>.
     */
    public Integer getFkBooking() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VBKA.BOOKING_R_CATEGORY.FK_CATEGORY</code>.
     */
    public void setFkCategory(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VBKA.BOOKING_R_CATEGORY.FK_CATEGORY</code>.
     */
    public Integer getFkCategory() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BookingRCategory.BOOKING_R_CATEGORY.FK_BOOKING;
    }

    @Override
    public Field<Integer> field2() {
        return BookingRCategory.BOOKING_R_CATEGORY.FK_CATEGORY;
    }

    @Override
    public Integer component1() {
        return getFkBooking();
    }

    @Override
    public Integer component2() {
        return getFkCategory();
    }

    @Override
    public Integer value1() {
        return getFkBooking();
    }

    @Override
    public Integer value2() {
        return getFkCategory();
    }

    @Override
    public BookingRCategoryRecord value1(Integer value) {
        setFkBooking(value);
        return this;
    }

    @Override
    public BookingRCategoryRecord value2(Integer value) {
        setFkCategory(value);
        return this;
    }

    @Override
    public BookingRCategoryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRCategoryRecord
     */
    public BookingRCategoryRecord() {
        super(BookingRCategory.BOOKING_R_CATEGORY);
    }

    /**
     * Create a detached, initialised BookingRCategoryRecord
     */
    public BookingRCategoryRecord(Integer fkBooking, Integer fkCategory) {
        super(BookingRCategory.BOOKING_R_CATEGORY);

        setFkBooking(fkBooking);
        setFkCategory(fkCategory);
    }
}
