/*
 * This file is generated by jOOQ.
 */
package de.VBKA.database.de_2fVBKA_2fdatabase;


import de.VBKA.database.de_2fVBKA_2fdatabase.tables.Account;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
