/*
 * This file is generated by jOOQ.
 */
package de_2fVBKA_2fdatabase.tables;


import de_2fVBKA_2fdatabase.Keys;
import de_2fVBKA_2fdatabase.Vbka;
import de_2fVBKA_2fdatabase.tables.records.CategoryRCategoryRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRCategory extends TableImpl<CategoryRCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>VBKA.CATEGORY_R_CATEGORY</code>
     */
    public static final CategoryRCategory CATEGORY_R_CATEGORY = new CategoryRCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoryRCategoryRecord> getRecordType() {
        return CategoryRCategoryRecord.class;
    }

    /**
     * The column <code>VBKA.CATEGORY_R_CATEGORY.FK_PARENT_CATEGORY</code>.
     */
    public final TableField<CategoryRCategoryRecord, Integer> FK_PARENT_CATEGORY = createField(DSL.name("FK_PARENT_CATEGORY"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>VBKA.CATEGORY_R_CATEGORY.FK_CHILD_CATEGORY</code>.
     */
    public final TableField<CategoryRCategoryRecord, Integer> FK_CHILD_CATEGORY = createField(DSL.name("FK_CHILD_CATEGORY"), SQLDataType.INTEGER.nullable(false), this, "");

    private CategoryRCategory(Name alias, Table<CategoryRCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private CategoryRCategory(Name alias, Table<CategoryRCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>VBKA.CATEGORY_R_CATEGORY</code> table reference
     */
    public CategoryRCategory(String alias) {
        this(DSL.name(alias), CATEGORY_R_CATEGORY);
    }

    /**
     * Create an aliased <code>VBKA.CATEGORY_R_CATEGORY</code> table reference
     */
    public CategoryRCategory(Name alias) {
        this(alias, CATEGORY_R_CATEGORY);
    }

    /**
     * Create a <code>VBKA.CATEGORY_R_CATEGORY</code> table reference
     */
    public CategoryRCategory() {
        this(DSL.name("CATEGORY_R_CATEGORY"), null);
    }

    public <O extends Record> CategoryRCategory(Table<O> child, ForeignKey<O, CategoryRCategoryRecord> key) {
        super(child, key, CATEGORY_R_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Vbka.VBKA;
    }

    @Override
    public UniqueKey<CategoryRCategoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6A;
    }

    @Override
    public List<ForeignKey<CategoryRCategoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_6A2, Keys.CONSTRAINT_6A28);
    }

    private transient Category _constraint_6a2;
    private transient Category _constraint_6a28;

    /**
     * Get the implicit join path to the <code>VBKA.CATEGORY</code> table, via
     * the <code>CONSTRAINT_6A2</code> key.
     */
    public Category constraint_6a2() {
        if (_constraint_6a2 == null)
            _constraint_6a2 = new Category(this, Keys.CONSTRAINT_6A2);

        return _constraint_6a2;
    }

    /**
     * Get the implicit join path to the <code>VBKA.CATEGORY</code> table, via
     * the <code>CONSTRAINT_6A28</code> key.
     */
    public Category constraint_6a28() {
        if (_constraint_6a28 == null)
            _constraint_6a28 = new Category(this, Keys.CONSTRAINT_6A28);

        return _constraint_6a28;
    }

    @Override
    public CategoryRCategory as(String alias) {
        return new CategoryRCategory(DSL.name(alias), this);
    }

    @Override
    public CategoryRCategory as(Name alias) {
        return new CategoryRCategory(alias, this);
    }

    @Override
    public CategoryRCategory as(Table<?> alias) {
        return new CategoryRCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CategoryRCategory rename(String name) {
        return new CategoryRCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CategoryRCategory rename(Name name) {
        return new CategoryRCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CategoryRCategory rename(Table<?> name) {
        return new CategoryRCategory(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
